version: "3"

services:
    db:
        image: mysql:8.0.22

        environment:
            MYSQL_DATABASE: 'relDesigns'
            MYSQL_ROOT_PASSWORD: '1234'
        ports:
            - 3306:3306
    web:
        image: web:latest
        build: ./relDesigns
        ports:
            - 8443:8443
        links:
            - db
            - servicio
        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql://db:/relDesigns
        restart: unless-stopped

    servicio:
        image: servicio:latest
        build: ./Servicio_Interno
        ports:
            - 8011:8011
        links:
            - db
        environment:
            - SPRING_JPA_HIBERNATE_DLL-AUTO=update
        
        restart: unless-stopped